# Generated by Django 5.2.6 on 2025-09-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_day_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='entered_bodyweight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='day',
            name='entered_meal',
            field=models.BooleanField(default=False),
        ),
    ]
