# Generated by Django 5.2.6 on 2025-09-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('calories', models.IntegerField(null=True)),
                ('protein', models.IntegerField(null=True)),
                ('fat', models.IntegerField(blank=True, null=True)),
                ('carb', models.IntegerField(blank=True, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.day')),
            ],
        ),
    ]
