# Generated by Django 5.2.6 on 2025-12-12 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcounter', '0002_alter_food_day'),
        ('core', '0009_alter_profile_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='day',
        ),
        migrations.AddField(
            model_name='food',
            name='calcium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='fdc_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='iron',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='magnesium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='postassium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_e',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='zinc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='IngredientComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.FloatField()),
                ('complex_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='calcounter.food')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_ingredient_of', to='calcounter.food')),
            ],
            options={
                'unique_together': {('complex_food', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(related_name='used_in_foods', through='calcounter.IngredientComposition', to='calcounter.food'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.day')),
            ],
        ),
        migrations.CreateModel(
            name='MealConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_g', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcounter.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcounter.meal')),
            ],
            options={
                'unique_together': {('meal', 'food')},
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='foods_consumed',
            field=models.ManyToManyField(related_name='consumed_in_meals', through='calcounter.MealConsumption', to='calcounter.food'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('food', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe', to='calcounter.meal')),
            ],
        ),
    ]
