# Generated by Django 5.2.6 on 2025-12-12 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcounter', '0003_remove_food_day_food_calcium_food_cholesterol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
