# Generated by Django 5.2.6 on 2025-12-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcounter', '0005_remove_food_is_template_remove_food_postassium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='status',
            field=models.CharField(choices=[('s', 'IN STOCK'), ('l', 'LOW_STOCK'), ('o', 'OUT_OF_STOCK')], default='o', max_length=1),
        ),
    ]
