# Generated by Django 5.2.6 on 2025-12-26 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcounter', '0006_alter_pantryitem_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealconsumption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='units',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealconsumption',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calcounter.meal'),
        ),
        migrations.AlterField(
            model_name='mealconsumption',
            name='serving_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='status',
            field=models.CharField(choices=[('s', 'IN STOCK'), ('l', 'LOW STOCK'), ('o', 'OUT OF STOCK')], default='o', max_length=1),
        ),
    ]
