# Generated by Django 5.2.6 on 2025-12-27 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcounter', '0007_alter_mealconsumption_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealconsumption',
            old_name='serving_g',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='pantryitem',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='mealconsumption',
            name='units',
        ),
        migrations.CreateModel(
            name='FoodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gram_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_standard', models.BooleanField(default=False, help_text="Is this a standard unit (like 'grams')?")),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='calcounter.food')),
            ],
            options={
                'unique_together': {('food', 'name', 'creator')},
            },
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='calcounter.foodunit'),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='calcounter.foodunit'),
        ),
    ]
