# Generated by Django 5.2.6 on 2025-12-31 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcounter', '0008_rename_serving_g_mealconsumption_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='quantity_g',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='calcounter.foodunit'),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='status',
            field=models.CharField(choices=[('s', 'IN STOCK'), ('l', 'LOW STOCK'), ('o', 'NO STOCK')], default='o', max_length=1),
        ),
    ]
