# Generated by Django 5.2.6 on 2026-01-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcounter', '0009_rename_quantity_g_ingredient_amount_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
