# Generated by Django 5.2.6 on 2026-01-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcounter', '0010_pantryitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(blank=True, help_text='in minutes', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, help_text='Step by step instructions', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(blank=True, help_text='in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='status',
            field=models.CharField(choices=[('s', 'IN STOCK'), ('l', 'LOW STOCK'), ('o', 'OUT OF STOCK')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='food',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe', to='calcounter.food'),
        ),
    ]
