# Generated by Django 5.2.6 on 2026-01-08 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcounter', '0011_remove_recipe_name_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='calcium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='carb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='cholesterol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='fiber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='iron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='magnesium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='protein',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='sugar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='vitamin_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='vitamin_b12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='vitamin_b6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='vitamin_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='vitamin_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='vitamin_e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealconsumption',
            name='zinc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealconsumption',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calcounter.food'),
        ),
    ]
