# Generated by Django 5.2.6 on 2026-01-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcounter', '0012_food_is_active_mealconsumption_calcium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealconsumption',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
