# Generated by Django 5.2.6 on 2026-02-04 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bodypart', models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('RS', 'Rear Shoulder'), ('CH', 'Chest'), ('TI', 'Tricep'), ('LS', 'Lateral Shoulder'), ('FS', 'Front Shoulder'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ad/Abductor'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2)),
                ('category', models.CharField(choices=[('M', 'Machine'), ('C', 'Cable'), ('B', 'Barbell'), ('D', 'Dumbbell')], max_length=1)),
                ('is_premium', models.BooleanField(default=False)),
                ('pack_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bodypart', models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('RS', 'Rear Shoulder'), ('CH', 'Chest'), ('TI', 'Tricep'), ('LS', 'Lateral Shoulder'), ('FS', 'Front Shoulder'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ad/Abductor'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2)),
                ('secondary_bodypart', models.CharField(blank=True, choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('RS', 'Rear Shoulder'), ('CH', 'Chest'), ('TI', 'Tricep'), ('LS', 'Lateral Shoulder'), ('FS', 'Front Shoulder'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ad/Abductor'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2, null=True)),
                ('category', models.CharField(choices=[('M', 'Machine'), ('C', 'Cable'), ('B', 'Barbell'), ('D', 'Dumbbell')], max_length=1)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('base_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.movementlibrary')),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workouts.movement')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField(help_text='Weight used')),
                ('rir', models.PositiveIntegerField(blank=True, help_text='Reps in reserve', null=True)),
                ('rest', models.DurationField(blank=True, help_text='Rest time between sets', null=True)),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.lift')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('soreness', models.PositiveIntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('personal_records', models.PositiveIntegerField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='core.day')),
            ],
        ),
        migrations.AddField(
            model_name='lift',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='workouts.workout'),
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_types', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workouts.workouttype'),
        ),
        migrations.CreateModel(
            name='WeeklyVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('muscle_group', models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('RS', 'Rear Shoulder'), ('CH', 'Chest'), ('TI', 'Tricep'), ('LS', 'Lateral Shoulder'), ('FS', 'Front Shoulder'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ad/Abductor'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2)),
                ('set_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'start_date', 'muscle_group')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutTypeBodypart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodypart', models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('RS', 'Rear Shoulder'), ('CH', 'Chest'), ('TI', 'Tricep'), ('LS', 'Lateral Shoulder'), ('FS', 'Front Shoulder'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ad/Abductor'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2)),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_muscles', to='workouts.workouttype')),
            ],
            options={
                'unique_together': {('workout_type', 'bodypart')},
            },
        ),
    ]
