# Generated by Django 5.2.6 on 2026-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movement',
            name='bodypart',
            field=models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('RS', 'R. Delts'), ('CH', 'Chest'), ('TI', 'Tricep'), ('LS', 'L. Delts'), ('FS', 'F. Delts'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ab|Ads'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movement',
            name='secondary_bodypart',
            field=models.CharField(blank=True, choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('RS', 'R. Delts'), ('CH', 'Chest'), ('TI', 'Tricep'), ('LS', 'L. Delts'), ('FS', 'F. Delts'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ab|Ads'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movementlibrary',
            name='bodypart',
            field=models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('RS', 'R. Delts'), ('CH', 'Chest'), ('TI', 'Tricep'), ('LS', 'L. Delts'), ('FS', 'F. Delts'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ab|Ads'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2),
        ),
        migrations.AlterField(
            model_name='weeklyvolume',
            name='muscle_group',
            field=models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('RS', 'R. Delts'), ('CH', 'Chest'), ('TI', 'Tricep'), ('LS', 'L. Delts'), ('FS', 'F. Delts'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ab|Ads'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2),
        ),
        migrations.AlterField(
            model_name='workouttypebodypart',
            name='bodypart',
            field=models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('RS', 'R. Delts'), ('CH', 'Chest'), ('TI', 'Tricep'), ('LS', 'L. Delts'), ('FS', 'F. Delts'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ab|Ads'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2),
        ),
    ]
