# Generated by Django 5.2.6 on 2025-10-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lift',
            name='bodypart',
            field=models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('CH', 'Chest'), ('TI', 'Tricep'), ('SH', 'Shoulder'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ad/Abuctor'), ('AB', 'Abs')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='lift',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lift',
            name='lift_type',
            field=models.CharField(choices=[('M', 'Machine'), ('B', 'Barbell'), ('D', 'Dumbbell')], max_length=1, null=True),
        ),
    ]
