# Generated by Django 5.2.6 on 2025-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_lift_bodypart_lift_is_template_lift_lift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='lift_type',
            field=models.CharField(choices=[('M', 'Machine'), ('C', 'Cable'), ('B', 'Barbell'), ('D', 'Dumbbell')], max_length=1, null=True),
        ),
    ]
