# Generated by Django 5.2.6 on 2026-01-27 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_lift_lift_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('muscle_group', models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('CH', 'Chest'), ('TI', 'Tricep'), ('SH', 'Shoulder'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ad/Abuctor'), ('AB', 'Abs')], max_length=2)),
                ('set_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'start_date', 'muscle_group')},
            },
        ),
    ]
