# Generated by Django 5.2.6 on 2026-01-29 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_weeklyvolume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='bodypart',
            field=models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('CH', 'Chest'), ('TI', 'Tricep'), ('SH', 'Shoulder'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ad/Abuctor'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='lift',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='workouts.workout'),
        ),
        migrations.AlterField(
            model_name='weeklyvolume',
            name='muscle_group',
            field=models.CharField(choices=[('BI', 'Bicep'), ('TR', 'Trap'), ('LT', 'Lat'), ('CH', 'Chest'), ('TI', 'Tricep'), ('SH', 'Shoulder'), ('QD', 'Quadricep'), ('HM', 'Hamstring'), ('CV', 'Calf'), ('HP', 'Ad/Abuctor'), ('GL', 'Glutes'), ('AB', 'Abs'), ('FO', 'Forearms')], max_length=2),
        ),
    ]
