# Generated by Django 5.2.6 on 2026-01-30 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_lift_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='workouts.workout'),
        ),
    ]
