name: Deploy Self-Stats
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Restart Containers
        run: |
          docker compose --env-file /home/github-runner/selfstats.env -f docker-compose.yml -f docker-compose.prod.yml --profile prod up -d --build

      - name: Prune Old Images
        run: docker image prune -f